language: node_js

node_js:
- "stable"
- '12.0'
- '11.0'
- '10.0'
- '9.0'
- '8.0'
- '7.0'
- '6.0'
- '5.0'
- '4.0'

matrix:
    fast_finish: true
    include:
        - node_js: stable
          env: COMMAND=test-browser
        - node_js: stable
          env: COMMAND=jest:cov
    allow_failures:
        - node_js: '7.0'
        - node_js: '6.0'
        - node_js: '5.0'
        - node_js: '4.0'

sudo: required

dist: trusty

cache:
    directories:
        - node_modules

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

after_script:
  - npx codecov

script: npm run ${COMMAND:-"test-node"}

env:
  - COMMAND=test-node

# env:
#   matrix:
#   - COMMAND=test-node
#   - COMMAND=test-browser

deploy:
  provider: npm
  email: contact@duzun.me
  api_key:
    secure: UeTmKdjg0MEmy8iK0ZmlmNww+hytHQoEkh7uhssV2Pizq2sSEKki9m64v7xe35Kwk38TcbMvrZkwtim/ZnZt1JJ2LOw8Ogz88OVviqAfkHOe2VRH8SrP3NpRFGFWLZ0JmvKGkvCLiDkLHiz+vSegUXDPwyGdpS932lyxJ5U3ntE=
  on:
    tags: true
    repo: duzun/p2peg.js
